### PR TITLE
Switch travis build system to Ubuntu 18.04 (Bionic)

### LINKED ISSUE #128: Travis builds are failing with libboost error
The last build of the master branch from 3 months ago is fine, but if you trigger a new build of the branch it fails for some compiler combinations. https://travis-ci.org/tumi8/vermont/branches

```
[ 89%] Linking CXX executable vermont
/usr/local/cmake-3.12.4/bin/cmake -E cmake_link_script CMakeFiles/vermont.dir/link.txt --verbose=1
/usr/lib/ccache/g++-6   -std=gnu++11 -Werror -Wall -pedantic -Wextra -Wno-unused-parameter -O2 -g -DNDEBUG  -rdynamic CMakeFiles/vermont.dir/src/vermont.cc.o  -o vermont src/modules/libmodules.a src/core/libcore.a src/common/anon/libanon.a src/common/ipfixlolib/libipfixlolib.a src/common/libcommon.a src/osdep/libosdep.a -lpthread -lsystemd -lczmq -lboost_regex -lboost_filesystem -lboost_system -lxml2 -lpcap -lpcap -lssl -lcrypto 
src/modules/libmodules.a(RegExFilter.cpp.o): In function `boost::cpp_regex_traits<char>::transform_primary[abi:cxx11](char const*, char const*) const':
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:965: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
src/modules/libmodules.a(RegExFilter.cpp.o): In function `boost::cpp_regex_traits<char>::transform[abi:cxx11](char const*, char const*) const':
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:961: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
collect2: error: ld returned 1 exit status
CMakeFiles/vermont.dir/build.make:97: recipe for target 'vermont' failed
make[2]: *** [vermont] Error 1
make[2]: Target 'CMakeFiles/vermont.dir/build' not remade because of errors.
```

### PR DESCRIPTION
**Pull request by constcast**
This pull request allows building Vermont on newer Linux distros (e.g. Ubuntu 18.04 (Bionic)) and switches the build system on Travis to Bionic as default build system.

One requirement for supporting newer distros is to require openssl >= 1.1.0, which is incompatible to older versions. This drops support for building Vermont with openssl prior to 1.1.0

Fixes #128

### CODE REVIEW

**Comment by nickbroon** [comment]
The changes to require and port the code to a modern ssl look fine.
I'm happy with move to basing on 1.1.0 ssl and using bionic as base for the Travis test builds.
(My main concerns are the Vermont continues to build on Debian Stretch and Buster).
Eventually the Vermont test-suite needs expanded so that some real tests of the code can be executed during the Travis run.

**Comment by constcast** [comment]
Stretch is a problem. I realized that the dependency is not 1.1.0 but 1.1.1. This is due to the use of DTLS_get_data_mtu, which was introduced in this version. Strech is still on 1.1.0, so this isn't going to work. 

I think I have to look into this. 

DTLS_get_data_mtu accounts for record header, encryption and authentication overhead, which we did not do in the past. But I think this should be done, so DTLS_get_data_mtu should be the right way to go. 

Some notes:

OpenConnect provides some DTLS_get_data_mtu replacement for openssl < 1.1.1 at (https://github.com/niw/openconnect/blob/master/openssl-dtls.c). But it needs an MTU as a starting point, which we no longer longer get. Maybe the MTU from the BIO could work as a starting point. 

But to get some better understanding of this, I have to do some experiments first.

**Comment by nickbroon** [comment]
Ouch, I hadn't noticed that DTLS_get_data_mtu() is 1.1.1 only. Yes, I agree that some replacement for the mtu needs to be found.

**Comment by nickbroon** [comment]
Thanks for adding openssl 1.1.0 support @constcast !

**Comment by constcast** [comment]
Merged :) Thx for reviewing

**Pull request merged**
