### PR TITLE
Brocade enhancements/fixes

### PR DESCRIPTION
**Pull request by nickbroon**
This branches represent the work we've (Brocade) made to enhance Vermont to integrate it into our Vrouter product.

In summary the changes include:
- Stricter compilation defaults
- Netflow V9 export protocol support
- A ZMQ IPFIX Receiver module
- Ability to reset module statistics
- IPV6 export support
- Journald logging support
- Fined grained logging options
- Improved support for daemonising
- Various bug fixes

The definitive location for open source code in Vrouter is:
http://www.brocade.com/en/overlay-pages/oscd/vyatta-subscription-edition-source-code.html
Vermont will appear in the 5600 4.0 release.

We will continue to add to this branch if/as we make further fixes/enhancements.

### CODE REVIEW

**Comment by bluca** [comment]
@ogasser - Hello, are you guys interested in this series (or a subset of) commits?

We merged into a single PR to aggregate our fixes in a single branch, to make our internal maintenance manageable, but I'm happy to split it out if you prefer. There are both features (Netflow V9 export, ZMQ support) and bug fixes. Please let us know, we are very happy to collaborate with you!

**Comment by nickbroon** [comment]
And significantly we've been using these changes without issue in our released product for a while now. I now consider these changes to be stable/robust.

**Comment by ogasser** [comment]
@bluca @nickbroon Thanks for your contributions!

I am still interested in merging these new features and fixes into the master branch. I would prefer to have separated PRs for each added feature or bug fix. That way it stays manageable for me with my rather constrained time on maintaining Vermont.

**Comment by nickbroon** [comment]
@ogasser that great, thanks! :-)

To hopefully keep things simple at our end as well, I'll work along the above branch of commits linearly, and open PR's for each section. By and large each commit stands alone and keeps everything working as it goes, though they do often depend on previous one. Hopefully we can avoid rebasing. :-)

**Comment by bluca** [comment]
@ogasser - sorry for the delay, busy with releases :-)
I've opened https://github.com/tumi8/vermont/pull/48 with the first of our changes. All the commits there are fixes to static analysis warnings, and a new target to run cppcheck through CMake, all changes that @nickbroon did.

**Comment by bluca** [comment]
Next one is up: https://github.com/tumi8/vermont/pull/49

**Comment by nickbroon** [comment]
Closing as it was all submitted in parts by @bluca, and merged by @ogasser.
Thanks guys!

**Pull request closed without merging**
