### PR TITLE
Use -Werror to fail the build on compiler warnings

### PR DESCRIPTION
**Pull request by nickbroon**
Use make -k so that all warnings are ouput if there are any.
This is the future :-)

### CODE REVIEW

**Comment by nickbroon** [comment]
I expect this to fail for the moment

**Comment by nickbroon** [comment]
So very close now! Just a couple of fall-through errors left. :-)
https://travis-ci.org/tumi8/vermont/jobs/329526027

**Comment by nickbroon** [comment]
The future has arrived! :-) It now builds cleanly with `-Werror` enabled.

**Comment by ogasser** [comment]
Very well done @evintila @nickbroon @bluca ! 🎉 🎊

**Pull request merged**
