### PR TITLE
Use XML ID as Sensors module id in receivers

### PR DESCRIPTION
**Pull request by bluca**
Very useful for debugging

### CODE REVIEW

**Comment by bluca** [comment]
Added another commit that fixes a format error flagged by static analysis

**Comment by ogasser** [comment]
Looks good!

**Comment by bluca** [comment]
Thank you! This was the last one from our queue, we are now in sync :-)
There is still work in progress for more features/bug fixes, which we'll send when it's completed.

**Comment by ogasser** [comment]
Great to hear!

**Pull request merged**
