### PR TITLE
Add a logging attribute to the ipfix config element

### PR DESCRIPTION
**Pull request by nickbroon**
This allows the logging level to set as part of configuration, instead
of having to use the `-l` CLI option. This mean it can also be changed
dynamically when the config file is re-read for changes.

### CODE REVIEW

**Comment by nickbroon** [comment]
Note that the Travis CI failures are completely unrelated to this change. (they probably relate to #128 )

**Comment by nickbroon** [comment]
@ogasser have you had chance to have a look at this? It would be great to get this merged.

**Comment by constcast** [comment]
I like the idea of being able to change the logging level in the configuration, and to change the log-level through reconfiguration. 

The change does overwrite the command line parameter, should one be given, though. Can you add a hint to the command line switch -l and -d to indicate that this can be overwritten by the configuration file?

**Comment by nickbroon** [comment]
Yes, adding it to the help output is good idea, thanks. I've done that.

**Comment by nickbroon** [comment]
@constcast is this now suitable for merging?
(I'm currently carrying this a patch against my deployment)

**Comment by constcast** [comment]
Hi nick,
thanks for bringing this up again.

I started looking at the pull request, but didn't complete my thought process. We have a couple of options related to logging (and I don't know if I have seen them all right now). What I've seen so far is

- log level
- syslog
- logging to journald

Shouldn't we allow configuring these via the XML, too?

Another thing that I'm not sure is: In case of a reconfiguration, we check the configuration file and only apply the changes when the configuration has been validated. The new log level would be applied directly, even if the rest of the configuration file is not valid.. That's probably not what we want.

I'm thinking about introducing a configuration module, similar to the sensorManager that allows to configure the three logging options. The module can then be applied during re-configuration after the config graph has been valid.

What do you think?

**Comment by nickbroon** [comment]
I think the problem with allowing configuring syslog/journal is that these are also controlled by compile time flags, so the binary may or may not have support for these. I'm not sure adding the complexity deal with this in the code is worth it. And while I can imagine people wanting to dynamically changing the logging level via the config reload, and I'm not sure changing method (syslog/journal/stdout) is really normal case, as this usually a daemon under the control of systemd/init.d. So I'm not sure a whole configuration module is necessary, and as logging applies across all modules I think having it as element of the vermont top level sort of logically makes sense.

Let me look at the config validation step you mentioned to see about only applying the logging level when the whole configuration has been validated. (though interestingly changing the logging level might actually help with analysising config that fails to be validate :-) ). Perhaps that could be considered as afollow up PR?

**Comment by constcast** [comment]
I see the point. Maybe that's the easiest solution. 

While testing, I came across two things:

  - We should have a message from ConfigManager that indicates that he changed the log level because of the configuration (this can help debug issues where an unsuspecting user changes the log level on the command line but this is overwritten) 
  - Invalid values of the attribute do not lead to an error message, but a silent keeping of the old level. I think we should have an error message if the value in the config is not valid (but I think we might proceed with the old log level)

**Comment by nickbroon** [comment]
Both good points @constcast . I look to address and update this PR.
I'll also fix the cli option handling code for logging level, that has the same problem with silently ignoring invalid input.

``` C
case 'l':
			msg_setlevel(parse_log_level(optarg));
			break;
```

**Comment by nickbroon** [comment]
I've updated the PR to log an error if the logging level is not recognised but continue anyway, and log the change of level.

**Comment by constcast** [comment]
Looks good. I fixed a merge problem that was introduced by one of the last pulls and merged it

**Comment by nickbroon** [comment]
Fab, thanks @constcast ! :-)

**Pull request merged**
