### PR TITLE
Install correctly named README.md

### PR DESCRIPTION
**Pull request by nickbroon**
otherwise make install step will fail.

### CODE REVIEW

**Comment by ogasser** [comment]
Is is possible to run `make install` in travis (either container or VM env) to catch these errors in the future?

**Comment by bluca** [comment]
yes - just configure cmake with a user-accessible prefix like /tmp and add make install to the script line

**Comment by nickbroon** [comment]
Snap, I was doing just that. :-)
I'll add it to the PR.

**Comment by ogasser** [comment]
Great!

**Pull request merged**
